- hosts: ssr
  name: Run the SSR service based on its latest (blubber-based) image
  tasks:
    - name: Ensure docker is installed
      package:
          name: docker-ce
          state: present

    - name: Ensure curl is installed
      package:
        name: curl
        state: present

    - name: Ensure project directory exists
      file:
          path: "{{ PATH }}"
          state: directory

    - name: Ensure README is in place
      copy:
        src: files/README.md
        dest: "{{ PATH }}/README.md"
        owner: "root"
        group: "root"
        mode: 0644

    - name: Ensure updater is in place
      template:
          src: templates/updater.sh.j2
          dest: "{{ PATH }}/updater.sh"
          owner: "root"
          group: "root"
          mode: 0744

    - name: Ensure updater is configured in crontab
      cron:
          name: Termbox updater
          job: "{{ PATH }}/updater.sh"
          minute: "*/{{ UPDATE_DURATION }}"
          user: root
          state: present

    - name: Ensure service is configured
      template:
        src: templates/termbox.service.j2
        dest: "/lib/systemd/system/termbox.service"
        owner: "root"
        group: "root"
        mode: 0644

    - name: Ensure systemd is using latest config
      systemd:
        daemon_reload: yes

    - name: Ensure the termbox service is running with the latest config
      systemd:
        state: restarted
        name: termbox
